# Generated by Django 2.2.13 on 2020-06-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='adress',
            field=models.CharField(default='Rua: 123', max_length=50),
        ),
        migrations.AddField(
            model_name='validation',
            name='cel',
            field=models.CharField(default='41 123451234', max_length=14),
        ),
        migrations.AddField(
            model_name='validation',
            name='cep',
            field=models.CharField(default='12345-123', max_length=9),
        ),
        migrations.AddField(
            model_name='validation',
            name='distric',
            field=models.CharField(default='Centro', max_length=30),
        ),
        migrations.AddField(
            model_name='validation',
            name='estate',
            field=models.CharField(default='Parana', max_length=20),
        ),
        migrations.AddField(
            model_name='validation',
            name='number',
            field=models.CharField(default='123', max_length=4),
        ),
        migrations.AddField(
            model_name='validation',
            name='rg',
            field=models.CharField(default='12345678-PR', max_length=13),
        ),
    ]
