# Generated by Django 2.2.13 on 2020-06-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0003_validation_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='rg',
            field=models.CharField(default='123456789', max_length=9),
        ),
    ]
