# Generated by Django 2.2.13 on 2020-06-15 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0005_auto_20200615_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validation',
            old_name='number',
            new_name='num',
        ),
        migrations.RenameField(
            model_name='validation',
            old_name='estate',
            new_name='state',
        ),
    ]
