# Generated by Django 2.2.13 on 2020-06-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0006_auto_20200615_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
