# Generated by Django 2.2.13 on 2020-06-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0007_auto_20200615_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='birth_date',
            field=models.CharField(max_length=9),
        ),
    ]
