# Generated by Django 2.2.13 on 2020-06-16 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0008_auto_20200615_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validation',
            old_name='distric',
            new_name='district',
        ),
    ]
