# Generated by Django 2.2.13 on 2020-06-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200613_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='local',
            field=models.CharField(default='Centro', max_length=50),
        ),
    ]
